# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T09:00:20+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class BalancePlatformNotificationResponse(BaseModel):
    notificationResponse: Optional[str] = Field(
        None,
        description='Respond with **HTTP 200 OK** and `[accepted]` in the response body to [accept the webhook](https://docs.adyen.com/development-resources/webhooks#accept-notifications).',
    )


class Type(Enum):
    balancePlatform_report_created = 'balancePlatform.report.created'


class Resource(BaseModel):
    balancePlatform: Optional[str] = Field(
        None, description='The unique identifier of the balance platform.'
    )
    creationDate: Optional[datetime] = Field(
        None,
        description='The date and time when the event was triggered, in ISO 8601 extended format. For example, **2020-12-18T10:15:30+01:00**.',
    )
    id: Optional[str] = Field(None, description='The ID of the resource.')


class ResourceReference(BaseModel):
    description: Optional[str] = Field(
        None, description='The description of the resource.'
    )
    id: Optional[str] = Field(
        None, description='The unique identifier of the resource.'
    )
    reference: Optional[str] = Field(
        None, description='The reference for the resource.'
    )


class ReportNotificationData(BaseModel):
    accountHolder: Optional[ResourceReference] = Field(
        None, description='The account holder related to the report.'
    )
    balanceAccount: Optional[ResourceReference] = Field(
        None, description='The balance account related to the report.'
    )
    balancePlatform: Optional[str] = Field(
        None, description='The unique identifier of the balance platform.'
    )
    creationDate: Optional[datetime] = Field(
        None,
        description='The date and time when the event was triggered, in ISO 8601 extended format. For example, **2020-12-18T10:15:30+01:00**.',
    )
    downloadUrl: str = Field(
        ...,
        description='The URL at which you can download the report. To download, you must authenticate your GET request with your [API credentials](https://docs.adyen.com/api-explorer/#/balanceplatform/latest/overview).',
    )
    fileName: str = Field(..., description='The filename of the report.')
    reportType: str = Field(..., description='Type of report.')


class ReportNotificationRequest(BaseModel):
    data: ReportNotificationData = Field(..., description='Contains event details.')
    environment: str = Field(
        ...,
        description='The environment from which the webhook originated.\n\nPossible values: **test**, **live**.',
    )
    type: Type = Field(..., description='Type of notification.')
